# Generated by Django 4.0.4 on 2023-03-24 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='tag name', max_length=50, unique=True)),
                ('image', models.URLField(help_text='link of the tag image')),
                ('redirect', models.URLField(help_text='link where the tag redirects')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='tool name', max_length=50, unique=True)),
                ('version', models.CharField(help_text='tool version (e.g. 1.2.5)', max_length=20)),
                ('image', models.URLField(help_text='link of the tool image', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='project name', max_length=80, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='project start date')),
                ('last_update', models.DateField(auto_now_add=True, help_text='project last update date')),
                ('logo', models.URLField(help_text='link of the project logo', null=True)),
                ('web_page', models.URLField(help_text='link of the project web page', null=True)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('repo', models.URLField(help_text='link of the project repository', null=True)),
                ('license', models.CharField(default='MIT', help_text='project license name (e.g. MIT, GPL-3.0, etc.)', max_length=20)),
                ('install', models.TextField(null=True)),
                ('run', models.TextField(null=True)),
                ('build', models.TextField(null=True)),
                ('test', models.TextField(null=True)),
                ('deploy', models.TextField(null=True)),
                ('roadmap', models.TextField(null=True)),
                ('tags', models.ManyToManyField(help_text='project tags', to='api.tag')),
                ('tools', models.ManyToManyField(help_text='project tools', to='api.tool')),
                ('user', models.ForeignKey(help_text='project owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='media name', max_length=80, unique=True)),
                ('link', models.URLField(help_text='link of the media source')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', help_text='media type', max_length=10)),
                ('project', models.ForeignKey(help_text='from project', on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='contact element name', max_length=50, unique=True)),
                ('image', models.URLField(help_text='link of the contact element image')),
                ('redirect', models.URLField(help_text='link where the contact element redirects')),
                ('user', models.ForeignKey(help_text='from user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
