# Generated by Django 4.0.4 on 2023-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deploy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='install',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.URLField(blank=True, help_text='link of the project logo', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.URLField(blank=True, help_text='link of the project repository', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='roadmap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='run',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_page',
            field=models.URLField(blank=True, help_text='link of the project web page', null=True),
        ),
    ]
