# Generated by Django 4.0.4 on 2023-03-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBadges',
            new_name='UserBadge',
        ),
    ]
