# Generated by Django 4.0.4 on 2023-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_userbadges_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='badges',
        ),
        migrations.AddField(
            model_name='user',
            name='web_page',
            field=models.URLField(blank=True),
        ),
    ]
