# Generated by Django 4.0.4 on 2023-03-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_build_alter_project_deploy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='redirect',
            field=models.TextField(help_text='link where the contact element redirects', max_length=200),
        ),
    ]
