# Generated by Django 4.0.4 on 2023-03-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contact_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='redirect',
            field=models.URLField(blank=True, help_text='official page or docs of the tool', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.URLField(blank=True, help_text='link of the contact element image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.URLField(blank=True, help_text='link of the tag image'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='version',
            field=models.CharField(blank=True, help_text='tool version (e.g. 1.2.5)', max_length=20),
        ),
    ]
