# Generated by Django 4.0.4 on 2023-03-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_roadmap_alter_command_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.TextField(null=True),
        ),
    ]
