# Generated by Django 4.0.4 on 2023-03-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_link_media_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
