# Generated by Django 4.0.4 on 2023-03-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_command_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcommand',
            name='command_type',
            field=models.CharField(choices=[('build', 'Build'), ('test', 'Test'), ('deploy', 'Deploy'), ('run', 'Run'), ('install', 'Install')], default='install', max_length=8),
        ),
    ]
