# Generated by Django 4.0.4 on 2023-03-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='details',
            field=models.TextField(blank=True, help_text='tag details', max_length=200),
        ),
    ]
