# Generated by Django 4.0.4 on 2023-03-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_projectcommand_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(null=True, upload_to='imgs/project'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.FileField(null=True, upload_to='imgs/tools'),
        ),
    ]
