# Generated by Django 4.0.4 on 2023-03-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_logo_alter_tool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
