# Generated by Django 4.0.4 on 2023-03-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tag_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='roadmap',
            field=models.TextField(default=''),
        ),
    ]
