# Generated by Django 4.0.4 on 2023-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_project_logo_alter_tool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badges',
            field=models.ManyToManyField(to='api.badge'),
        ),
        migrations.DeleteModel(
            name='ProjectBadge',
        ),
    ]
