# Generated by Django 4.0.4 on 2023-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_badges_delete_projectbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcommand',
            name='command',
        ),
        migrations.RemoveField(
            model_name='projectcommand',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcommand',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='projectroadmap',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectroadmap',
            name='road_map',
        ),
        migrations.RemoveField(
            model_name='projecttool',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttool',
            name='tool',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='commands',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='roadmap',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(to='api.tool'),
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='ProjectCommand',
        ),
        migrations.DeleteModel(
            name='ProjectRoadMap',
        ),
        migrations.DeleteModel(
            name='ProjectTool',
        ),
        migrations.DeleteModel(
            name='RoadMap',
        ),
    ]
