# Generated by Django 4.0.4 on 2023-04-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_project_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(help_text='media name', max_length=80),
        ),
    ]
