# Generated by Django 4.0.4 on 2023-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='done',
            field=models.BooleanField(default=False, help_text='project is done'),
        ),
    ]
