# Generated by Django 4.0.4 on 2023-04-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_project_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='done',
            new_name='is_done',
        ),
    ]
