# Generated by Django 4.0.4 on 2023-03-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_commands_project_build_project_deploy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='redirect_link',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_link',
            new_name='redirect',
        ),
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('link', models.URLField()),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
