# Generated by Django 4.0.4 on 2023-04-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_done_project_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('personal', 'personal'), ('client', 'client')], default='personal', help_text='project type', max_length=10),
        ),
    ]
