# Generated by Django 4.0.4 on 2023-03-24 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_contact_remove_user_tags_alter_tag_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clone_repo',
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.URLField(help_text='link of the contact element image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='contact element name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='redirect',
            field=models.URLField(help_text='link where the contact element redirects'),
        ),
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.URLField(help_text='link of the media source'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', help_text='media type', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(help_text='media name', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='project',
            field=models.ForeignKey(help_text='from project', on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_update',
            field=models.DateField(auto_now_add=True, help_text='project last update date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(default='MIT', help_text='project license name (e.g. MIT, GPL-3.0, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.URLField(help_text='link of the project logo', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='project name', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.URLField(help_text='link of the project repository', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='project start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(help_text='project tags', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(help_text='project tools', to='api.tool'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(help_text='project owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_page',
            field=models.URLField(help_text='link of the project web page', null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.URLField(help_text='link of the tag image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='tag name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='redirect',
            field=models.URLField(help_text='link where the tag redirects'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.URLField(help_text='link of the tool image', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(help_text='tool name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='version',
            field=models.CharField(help_text='tool version (e.g. 1.2.5)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(help_text='contact information of the user', to='api.contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='web_page',
            field=models.URLField(blank=True, help_text="link to the user's web page"),
        ),
    ]
