# Generated by Django 4.0.4 on 2023-05-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_tag_image_remove_tag_redirect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='version',
        ),
    ]
