# Generated by Django 4.0.4 on 2023-06-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_project_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='svg',
            field=models.URLField(blank=True, help_text='link of the contact element image (in svg format)'),
        ),
    ]
