# Generated by Django 4.0.4 on 2023-07-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_contact_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='contact element name', max_length=50),
        ),
    ]
