# Generated by Django 4.0.4 on 2023-07-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_contact_image_alter_contact_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location_pc',
            field=models.CharField(blank=True, help_text='project location in pc', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_remote',
            field=models.BooleanField(default=False, help_text='project is updated in remote repo'),
        ),
    ]
