# Generated by Django 4.0.4 on 2023-07-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_project_location_pc_project_updated_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated_remote',
            field=models.BooleanField(default=False, editable=False, help_text='project is updated in remote repo'),
        ),
    ]
