# Generated by Django 4.0.4 on 2023-10-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_project_updated_remote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='svg',
        ),
        migrations.AddField(
            model_name='contact',
            name='svg_path',
            field=models.TextField(blank=True, help_text='svg path of the contact element image', max_length=1000),
        ),
    ]
