# Generated by Django 4.0.4 on 2023-10-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_contact_svg_contact_svg_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='svg_path',
            field=models.TextField(blank=True, help_text='svg path of the contact element image', max_length=2000),
        ),
    ]
