# Generated by Django 4.0.4 on 2023-10-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_contact_svg_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='svg_path',
        ),
        migrations.AddField(
            model_name='contact',
            name='svg',
            field=models.URLField(blank=True, help_text='link of the contact element svg', max_length=600),
        ),
    ]
